- name: Newrelic Agent | Prepare install
  file: state=directory path=/etc/newrelic

- name: Newrelic Agent | Download
  get_url: 
    url: "https://oss.sonatype.org/content/repositories/releases/com/newrelic/agent/java/newrelic-agent/{{ newrelic_agent_version }}/newrelic-agent-{{ newrelic_agent_version }}.jar"
    dest: /etc/newrelic/
